### ISSUE TITLE
PaymentResponse missing filters

### ISSUE THREAD

**Issue by mattsaxon** [w3c/webpayments-methods-card#28]
The response from Basic Card does not specify the type of card that was selected.

This would be useful for the merchant to understand.

An example of the use of this would be where there is differential pricing between different instruments.

**Comment by zkoch** [comment]
By type do you mean credit, debit, or prepaid? Because I don't think many payment apps will know this, so I'm hesitant to put this in if merchants can't depend on it being accurate.

**Comment by mattsaxon** [comment]
So I would say network and type, but I would say that it is potentially optional, just as you've mentioned that the implementation of the filter is optional (and may be patchy)

**Comment by mattsaxon** [comment]
With regard to the patchy support for filter by network type (issue #19), I think this needs resolving, specifically to deal with differential pricing. If there are different prices specified for different instruments, what will be the behaviour if the payment app implementation cannot differentiate? Do we need to consider responding with the amount that was finally approved for payment also?

**Comment by marcoscaceres** [comment]
@mattsaxon, the different in charges is handled by PaymentRequest's modifiers, no? Also, once the merchant gets back the card, they can look up the type via the BIN.

**Comment by marcoscaceres** [comment]
that is, the merchant can't trust the browser to tell it what the type is... specially because they will need to adjust the total based on card type regardless... if the browser is modified to lie - or get's otherwise confused, then the merchant could end up charging the wrong amount. 

Bottom line: "merchants should trust... but always verify".

**Comment by marcoscaceres** [comment]
Closing this issue, as I don't think there is anything we can do here.
