### ISSUE TITLE
No description of BasicCardResponse's billingAddress

### ISSUE THREAD

**Issue by dbaron** [w3c/webpayments-methods-card#30]
The [section on `BasicCardResponse`](https://w3c.github.io/webpayments-methods-card/#basiccardresponse) is missing a description of the `billingAddress` dictionary member; it has descriptions of the other 5 members.

(I got here from https://github.com/w3ctag/spec-reviews/issues/152.)

**Comment by marcoscaceres** [comment]
I fixed this a while ago, but forgot to close
