### ISSUE TITLE
Adding support for "encrypted basic card"

### ISSUE THREAD

**Issue by cyberphone** [w3c/webpayments-methods-card#38]
Supporting external payment providers offering "secure payment pages" where the user fill-in card details etc. has the advantage that is relieves the merchant from PCI certification as well as dealing with payment networks.  _This is a very common arrangement_.

Although https://w3c.github.io/webpayments-methods-tokenization/index.html could address this problem, there is a (for this purpose NB), much simpler solution needing the following additional properties
- public encryption key
- key encryption algorithm
- content encryption algorithm

which if defined would return exactly the same data as "basic card" _but encrypted by the outsourced payments provider's public key_.  The data would preferably be encrypted using JOSE JWE.  The resulting Base64Url encoded "blob" could then be supplied as an argument to the redirect which currently usually happens after the customer have selected "card payment" relieving the end-user from filling in card data.

Only the targeted service provider would be able to decrypt such elements.

Outsourced payment services could make this new element _optional_ so that existing merchant solutions would continue exactly as today.

Security wise it is important noting that plain-text card data would (in addition to the outsourced payment provider), only be processed by trusted (built-in) browser software and the end-user. 

Note that this arrangement only requires the browser to encrypt data and that _no additional external service providers are introduced either._

**Comment by marcoscaceres** [comment]
@cyberphone, thanks! 

> This is a very common arrangement.

I'd like to hear more. Can you provide me some links to further reading? Who provides this arrangement? 

First question that comes to mind, why not just encrypt `PaymentResponse.toJSON()` with the three things above? If they need to be passed into the API, presumedly the client site can just do this using the Web Crypto API? (I have no idea what I'm talking about, btw... but that's just my initial reaction)

**Comment by cyberphone** [comment]
@marcoscaceres I believe I have encountered such arrangement many times.  Most of the big players probably including Worldpay provide such solutions.

https://en.wikipedia.org/wiki/List_of_online_payment_service_providers

The connection between Merchants and such providers are usually based on a URL with a small set of  parameters holding session id, merchant id, amount to pay, etc.  When ready it redirects to the merchant with the outcome of the payment.

Of course the merchant can encrypt card data as well.  The motives for doing it inside the browser (through the API) are two-fold: 

- It is non-trivial doing crypto
- Security-wise it seems more "correct" that card plain text never reaches (potentially non-secure) merchant code.  Such a thing _could_ have PCI implications

**Comment by marcoscaceres** [comment]
> @marcoscaceres I believe I have encountered such arrangement many times. Most of the big players probably including Worldpay provide such solutions.

Ok, excellent. So we should easily be able to get a list of exactly if anyone needs this from the WG members.

> Of course the merchant can encrypt card data as well. The motives for doing it inside the browser (through the API) are two-fold:

Right now I'm mostly interested to see how "non-trivial" it is to satisfy the use case with existing primitives (i.e., web crypto). It would be generally useful to be able to do something like JOSE - specially if you can could do: 

```JS
const encrypted = JOSE.encrypt(response.toJSON()). 
```

**Comment by marcoscaceres** [comment]
Looking at https://www.npmjs.com/package/node-jose - maybe could be used to solve this?

**Comment by cyberphone** [comment]
> Ok,  excellent. So we should easily be able to get a list of exactly if anyone needs this from the WG members.

Since the vast majority of the payment vendors are not WG members, and even fewer hang out on GitHub, that would (IMHO) not return an exhaustive response.

I would rather engage the members by asking: _How do you anticipate that the PaymentRequest API is to be used with providers of outsourced "Secure Payment Pages"_.  A possible answer is that PaymentRequest is outsourced as well but then the Merchant won't be able to use _other_ outsourced providers in the same setup.  BTW, how is PayPal supposed to work in this context?

Encrypting on the inside or on the outside is not only a technical issue, _it is a policy consideration_.  Personally I'm not (at all) into policy, so I try to come up with solutions that should comply with _any_ policy, be it sloppy or strict.

This topic seems like a possible work item for the https://www.w3.org/Payments/IG/wiki/Security_Task_Force.

The proposal was partly "inspired" by a similar concept featured in Android Pay
https://developers.google.com/web/fundamentals/discovery-and-monetization/payment-request/android-pay#integration_using_network_token
where the "App" does the encryption so the idea certainly isn't very novel :-)

**Comment by marcoscaceres** [comment]
> that would (IMHO) not return an exhaustive response.

We don't need exhausting, but we need somewhat representative and a few "yeah, we totally need this! We are currently hacking around this limitation with X". 

"X" is critical to the discussion to motivate any standardization. If there is no "X" today, then it's too early to be discussing standardization. 

We can also ask on the mailing list, if the community is not on GitHub. 

> I would rather engage the members by asking: ...

👍, email the WG. 

> BTW, how is PayPal supposed to work in this context?

We will find out really soon: they are working on a prototype with Google. Waiting to hear what they need.

**Comment by cyberphone** [comment]
>> BTW, how is PayPal supposed to work in this context?

> We will find out really soon: they are working on a prototype with Google. Waiting to hear what they need.

It looks to me (but I may surely be misinformed), that there is a generic issue with "Web only" payment methods hosted on secure servers and their connection to the PaymentRequest API.  Could a pre-defined "Redirect" payment method do the trick?

**Comment by ianbjacobs** [comment]
Hi all,
We long ago resolved not to add encryption to basic card. It's fine to have discussion about enhanced payment card payment methods (as we are doing in the tokenization task force) but the target should be "some new payment method."

Ian

**Comment by cyberphone** [comment]
For external developers like me the only important thing is that questions/suggestions are dealt with. Feel free moving this topic to whatever place you find suitable, hopefully excluding /dev/null :-)

@adrianhopebailie apparently suggested pretty much the same thing a year ago as well:
https://lists.w3.org/Archives/Public/public-payments-wg/2016Jul/0083.html

The difference with this renewed proposal, is that _it supports a fairly common web payment use case which isn't covered by the current spec_.  If the WG's _recommendation_ rather is that merchants should deal with encryption themselves, this ought to belong to some associated document as well.

**Comment by marcoscaceres** [comment]
@cyberphone, the solution is rarely "we need a standard" (that's the only solution when we have exhausted all other solutions). 

Please use what the platform already provides until it's demonstratively proven that it's broken and actually needs a standard. 

Right now, I'm just seeing words and no JS. Until I see JS and DOM APIs proving that it's broken, I'm inclined to close this.

**Comment by cyberphone** [comment]
Since the actual goal was _supporting external providers of secure payment pages in a meaningful way_,  your workaround (which then will be a de-facto standard), should be outlined in the best practices document.

**Comment by marcoscaceres** [comment]
@cyberphone, I completely agree. But *I don't know how to do it* AND *I'm not in a position to recommend best practice*: That's what I was trying to say above... we need to see how smart JS devs from large businesses will do this in practice, *on real sites*, and deployed at scale. 

Like, "Site X services 1,000,000 *secure* payment requests per hour, and they are doing it this way: 

```JS
<javascript goes here>
````

We (the WG members) can't prematurely say: "this is how you can do it best", because we don't actually know what is "best" right now. 

It would be completely irresponsible to make any such "best practice" recommendations, particularly coming from folks that barely know JavaScript or don't even own an online retail shop.

**Comment by adrianhopebailie** [comment]
Many of these use cases (where it's necessary to remove the merchant website from PCI scope) can be addressed by embedding an iframe in the checkout page that renders secure content from the third party payment provider and exposes the PaymentRequest API.

@zkoch did some work to ensure there is an appropriate attribute that can be set in the iframe to allow the PaymentRequest API to be called from that internal context.

**Comment by cyberphone** [comment]
@adrianhopebailie I must confess that I don't understand how that is supposed to work and https://github.com/w3c/payment-request-info/wiki/PaymentMethodPractice doesn't give any clues either.  What I described and requested is when a _merchant_ invokes the PaymentRequest and potentially targets a wide range of payment methods where outsourced secure card processing would be one.

**Comment by ianbjacobs** [comment]
@cyberphone,

You asked '"How do you anticipate that the PaymentRequest API is to be used with providers of outsourced "Secure Payment Pages".' I believe the answer is "With iframe,
the same way it is done today."

However just a moment ago you wrote " What I described and requested is when a *merchant* invokes the PaymentRequest..." That seems to be a separate question, not about outsourcing.

Different payment methods will support different features. Our expectation is that the Working Group will not discuss payment methods and their features exhaustively.

We are talking about tokenization of card payments and also credit transfers as you know.

So I'm trying to figure out whether:
 1) We already do what you want. (That is: use iframe for hosted calls to PR API.)
 2) We are already talking about what you want (That is: tokenization)
 3) We are not yet talking about what you want (and may not do so in the future.)

Ian
