### ISSUE TITLE
Relationship to PaymentRequest

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webpayments-methods-card#40]
The spec needs to state that [`PaymentMethodData.data`](https://w3c.github.io/payment-request/#dom-paymentmethoddata-data) is [`BasicCardRequest`](https://w3c.github.io/payment-method-basic-card/#basiccardrequest-dictionary) when  [`PaymentMethodData.supportedMethods`](https://w3c.github.io/payment-request/#dom-paymentmethoddata-supportedmethods) is `"basic-card"`.

**Comment by rsolomakhin** [comment]
Originally brought up in a Blink [intent to ship](https://groups.google.com/a/chromium.org/d/msg/blink-dev/PcG_926N4FA/-AMukfMMAwAJ). The spec also needs to mention the `data` in the `modifiers` field.

**Comment by marcoscaceres** [comment]
Thanks @rsolomakhin, will clarify.

**Comment by foolip** [comment]
Is there any normative change involved here? Looks like `PaymentMethodData` is used only in https://w3c.github.io/payment-request/#constructor and it just JSON-serializes the object and rethrows exceptions. Seems to me that either no normative change is needed, or it's in some place that doesn't operate on the IDL dictionaries but on the serialized JSON?

**Comment by marcoscaceres** [comment]
I just need to add a section that will say that an API needs to do the convertion. Sorry I've not gotten to it yet - busy trying to finish the PR spec's test suite. 

In reality, it doesn't change anything tho in implementations. The PR API says to do the conversion, and clearly a UA needs to do the conversion to the appropriate dictionaries.

**Comment by marcoscaceres** [comment]
Hopefully more clear now (input and output): 
https://w3c.github.io/payment-method-basic-card/#interfacing-with-a-payment-handler
