### ISSUE TITLE
Drop supportedTypes?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-methods-card#59]
As part of discussing PR API issue 753 [1] it has emerged that there are challenges in accurately determining at low cost the card type (credit, debit, prepaid). 

After asking a few of the WG participants whether they have heard significant demand for this feature, the initial responses have been "no." 

Therefore, I would like the group to explicitly consider whether to drop supportedTypes in this version of Basic Card.

[1] https://github.com/w3c/payment-request/issues/753

**Comment by mattsaxonwp** [comment]
I'd like to add a few data points to the ongoing discussion;

1. As @Krystosterone states [here](https://github.com/w3c/payment-request/issues/753#issuecomment-416292970), in the EU, differential pricing is now prohibited, for the UK this is as of January 2018, see this [article](https://www.moneysavingexpert.com/news/2018/01/cards-fees-to-be-banned-from-saturday/)

2. Whilst differential pricing for cards (and hence in basic-card spec) is no longer a requirement in the UK/EU, the ability to deliver differential pricing between payment methods I believe is still a valid use case.

3. Given the above restriction, I can vouch that certain merchants (specifically in the UK, my home country) have adopted a revised approach of simply not accepting certain types of card. Therefore I believe that filtering based on a deeper understanding than just network is still a requirement. (I attach a screen snip of one such payment process excluding retail credit cards)

![image](https://user-images.githubusercontent.com/17925307/46372274-97d27380-c682-11e8-9b81-4bd5d9478c5e.png)

Whilst I appreciate the implementation difficulties pertaining to accurate information regarding card types, I wanted to reaffirm the requirement, even if we choose to deprioritise and remove from this release. 

I suggest that if we do remove the capability from basic-card that we consider adding guidance to the Developer FAQ that Ian maintains.

**Comment by ianbjacobs** [comment]
@marcoscaceres,

At the 22 October FTF meeting [1] there was strong consensus to remote supportedTypes. (We also wanted to see a demo showing how retry() could be used in the case of a selected card not accepted by the merchant, but we didn't get to that.) 

I would like to request that you create a pull request for removing the feature that we can reference from a Call for Consensus.

Thanks!

(NOTE: As of right now these are draft minutes.)
[1] https://www.w3.org/2018/10/22-wpwg-minutes#item03

**Comment by marcoscaceres** [comment]
> At the 22 October FTF meeting [1] there was strong consensus to remote supportedTypes. (We also wanted to see a demo showing how retry() could be used in the case of a selected card not accepted by the merchant, but we didn't get to that.)

Sorry, TPAC was crazy busy. I'll  try to put something together (e.g., a short video). 

> I would like to request that you create a pull request for removing the feature that we can reference from a Call for Consensus.

Given #62, could you kindly begin the CFC.
