### ISSUE TITLE
Add Security Considerations and Privacy Considerations sections

### ISSUE THREAD

**Issue by adamroach** [w3c/webpayments-methods-card#6]
This is a recommendation from the Security and Privacy Checklist review. See https://docs.google.com/document/d/1w7ginyzNg-xZUmITK4vzcGUKB4gbMOAvlkWWaRtX14k/edit?usp=sharing for additional detail

This checklist analysis has indicated a number of privacy and security issues that pertain to the Basic Card Payment spec, and they should be incorporated into the document.

**Comment by adrianba** [comment]
Fixed by #7.
