### ISSUE TITLE
from a consumer POV

### ISSUE THREAD

**Issue by lucasverra** [w3c/webpayments-methods-card#76]
Is the objective of this specification to bring "easy checkout processes" on web with  `any` (credit, debit) cards , event if NOT associated with a big corp processor (apple, google, samsung) ? 

Thanks for clarifying 👍

**Comment by ianbjacobs** [comment]
@lucasverra, this API is not specific to any payment method or company. I'll close this issue but can reopen if there are questions you have about the specification details. Thanks!
