### ISSUE TITLE
Combine two algorithms into one if canMakePayment from PR API does not involve ph communication

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-methods-card#87]
Hi all,

One direction of thinking for the semantics of canMakePayment and hasEnrolledInstrument is captured in this blog post:
 https://www.w3.org/blog/wpwg/2020/01/17/working-with-canmakepayment-and-hasenrolledinstrument/

Namely: canMakePayment does not require the browser to communicate with the payment handler, while hasEnrolledInstrument does. 

If we move in that direction (see also this proposal [1]), then there should not be the need for both algorithms: "Steps to check if a payment can be made" and "Steps to check if an instrument is supported" because the API surface only needs one of them. They could be combined.

[1] https://docs.google.com/document/d/1C_xH-6sJb9UedrvifsvqS_2k_We0IlPSfWFo8Kg54ps/edit

**Comment by marcoscaceres** [comment]
Spec was gutted (such an awful metaphor). No longer applies.
