### ISSUE TITLE
Is this a REC-track document?

### ISSUE THREAD

**Issue by xfq** [w3c/webpayments-methods-card#88]
This spec seems to have normative content, but contains [noRecTrack: true](https://github.com/w3c/payment-method-basic-card/blob/c07025cad18851c5fa486c05ceb5d2cc872c9698/index.html#L42). Is that intended?

**Comment by ianbjacobs** [comment]
Short answer: Yes.

We've had discussion about this and 2 decisions to make it a Note.

**Comment by marcoscaceres** [comment]
Spec was gutted, so no longer relevant.
