### ISSUE TITLE
Drop references to now gone PaymentAddress and AddressErrors interfaces

### ISSUE THREAD

**Issue by tidoust** [w3c/webpayments-methods-card#89]
The `PaymentAddress` and `AddressErrors` interfaces were dropped from Payment Request in https://github.com/w3c/payment-request/pull/955

The "Payment Method: Basic Card" document still references them in the definition of [`BasicCardChangeDetails`](https://w3c.github.io/payment-method-basic-card/#webidl-1032216062) and [`BasicCardErrors`](https://w3c.github.io/payment-method-basic-card/#webidl-751346091), making the IDL inconsistent as a whole.

@ianbjacobs, looking at [minutes from a recent group call](https://www.w3.org/2021/04/29-wpwg-minutes#t01), I see that goal might be to deprecate the specification entirely. That would be a more radical way to fix the inconsistency. If it still gets published as a Note with IDL, it would still be good to resolve it properly.

**Comment by marcoscaceres** [comment]
Done. Spec was gutted.
